
# it is used to log the sql on console.
logging:
  #  pattern:
  #    level: "%5P ${HOSTNAME}"
  #    console:
  file:
    name: target/hibernate.log
  level:
    sql: debug
    web: debug
    '[com.example.crud]': DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${hibernate.db.url}
    user: ${hibernate.db.user}
    password: ${hibernate.db.password}

server:
  port: 9080