
# it is used to log the sql on console.
logging:
  #  pattern:
  #    level: "%5P ${HOSTNAME}"
  #    console:
  file:
    name: target/crud.log
  level:
    sql: debug
    web: debug
    '[com.example.crud]': DEBUG

spring:
  sql:
    like:
      operator: '%'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  h2:
    console:
      enabled: true
  datasource:
    url: ${crud.db.url}
    user: ${crud.db.user}
    password: ${crud.db.password}
#    url: ${CRUD_DB_URL}
#    user: ${CRUD_DB_USER}
#    password: ${CRUD_DB_PASSWORD}
#  cache:
#    type: caffeine
#    caffeine:
#      spec: maximumSize=5000, expireAfterAccess=300s
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: admin

#  datasource:
#    initialization-mode: always
#    data: classpath:data3.sql
#    schema: classpath:schema3.sql

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#      show-details: when-authorized

#generator:
#  strategy: sequence

server:
  port: 9080
#  servlet:
#    context-path: /news

spring.profiles.include: dev