#logging:
#  level:
#    s7.Application: WARN
#    org.springframework.web: ERROR
#    com.example.logging: DEBUG
#    # give your root package in place of com.example.logging
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
#  file:
#    name: api.log